spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: admin
    password: AAzz123svp1
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    flyway:
      baseline-on-migrate: true
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: car-master
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

webApp:
  url: https://wsnnhj-93-157-20-22.ru.tuna.am
  id: 771107152

telegrambots:
  bot:
    username: AutoResourseBot
    token: 8094223162:AAECxv7df6Aa1BCul9XCmC6Uu3tWYvVQ0JA